# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackchannel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
