# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('core', '0002_auto_20170103_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='conversation.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Command'), (2, 'Asking'), (3, 'Answered')], default=1),
        ),
    ]
